package org.axiom.tenet;

enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    AND, CLASS, ELSE, IF, NIL, FUN, FALSE, TRUE, OR, PRINT, RETURN, SUPER, THIS, VAR, WHILE, FOR,

    // Game theory tokens
    GAME, PLAYERS, STRATEGIES, PAYOFF, SOLVE, USING, COLON, IMPORT,

    // Mechanism design tokens
    TWEAK, FROM, TO, STEP,

    // Sequential game tokens
    SEQUENTIAL, NODE, MOVE, ARROW, VISUALIZE,

    EOF

}
